### ISSUE TITLE
change dockerfile python ver

### ISSUE THREAD

**Issue by PavelFalta** [PavelFaltaorg/NSQL_final#2]
python 3.11.2 is needed for game_server dockerfile

**Comment by JaroslavRadimsky** [comment]
![image](https://github.com/user-attachments/assets/5999d077-a9ee-4fe7-bab3-a0dd8b41dfcd)
available options from docker
@PavelFalta

**Comment by PavelFalta** [comment]
lets try ```3.11-alpine```
@jardik14

**Comment by JaroslavRadimsky** [comment]
went with `3.11-bullseye` alpine was unable to install all requirements
